### ISSUE TITLE
导入项目报错

### ISSUE THREAD

**Issue by BlainPeng** [ZhaoKaiQiang/JianDanRxJava#1]
mAdapter = new PictureAdapter(getActivity(), this, mRecyclerView, mType);
mAdapter = new VideoAdapter(getActivity(), this, mRecyclerView);

这里的getActivity需要强转成BaseActivity

**Comment by ZhaoKaiQiang** [comment]
已修复，多谢

**Comment by BlainPeng** [comment]
我第一次安装时不打开网络，未弹出你代码里写的去打开网络的MaterialDialog

**Comment by ZhaoKaiQiang** [comment]
现在的设计是网络变化并且无网络时弹出，第一次安装时无网络变化广播
