### ISSUE TITLE
com.squareup.okhttp.Response报错，必须修改为okhttp3.response

### ISSUE THREAD

**Issue by tmexcept** [ZhaoKaiQiang/JianDanRxJava#3]
com.socks.jiandan.net.parser下的所有的类文件中导入的com.squareup.okhttp.Response必须修改为okhttp3.response才不会有编译错误，这是怎么回事？
![image](https://cloud.githubusercontent.com/assets/10299901/12230595/93db33c2-b88c-11e5-8380-8c6b19598ba2.png)

**Comment by ZhaoKaiQiang** [comment]
已更新，OkHttp升级了
